#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouSoftBathPayVideo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="BathDB")]
	public partial class BathDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPayMsg(PayMsg instance);
    partial void UpdatePayMsg(PayMsg instance);
    partial void DeletePayMsg(PayMsg instance);
    partial void InsertOptions(Options instance);
    partial void UpdateOptions(Options instance);
    partial void DeleteOptions(Options instance);
    #endregion
		
		public BathDBDataContext() : 
				base(global::YouSoftBathPayVideo.Properties.Settings.Default.BathDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BathDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BathDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BathDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BathDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PayMsg> PayMsg
		{
			get
			{
				return this.GetTable<PayMsg>();
			}
		}
		
		public System.Data.Linq.Table<Options> Options
		{
			get
			{
				return this.GetTable<Options>();
			}
		}
	}
	
	[Table(Name="dbo.PayMsg")]
	public partial class PayMsg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _systemId;
		
		private string _ip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsystemIdChanging(string value);
    partial void OnsystemIdChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    #endregion
		
		public PayMsg()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_systemId", DbType="NVarChar(MAX)")]
		public string systemId
		{
			get
			{
				return this._systemId;
			}
			set
			{
				if ((this._systemId != value))
				{
					this.OnsystemIdChanging(value);
					this.SendPropertyChanging();
					this._systemId = value;
					this.SendPropertyChanged("systemId");
					this.OnsystemIdChanged();
				}
			}
		}
		
		[Column(Storage="_ip", DbType="NVarChar(MAX)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Options")]
	public partial class Options : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _companyName;
		
		private string _companyCode;
		
		private string _companyPhone;
		
		private string _companyAddress;
		
		private System.Nullable<int> _取消开牌时限;
		
		private System.Nullable<int> _取消开房时限;
		
		private System.Nullable<int> _删除支出时限;
		
		private System.Nullable<int> _退钟时限;
		
		private System.Nullable<int> _技师条数;
		
		private System.Nullable<bool> _启用鞋部;
		
		private System.Nullable<int> _鞋部条数;
		
		private System.Nullable<bool> _启用会员卡密码;
		
		private System.Nullable<bool> _输入手牌;
		
		private System.Nullable<bool> _启用结账监控;
		
		private string _结账视频长度;
		
		private System.Nullable<bool> _启用手牌锁;
		
		private System.Nullable<int> _开业时间;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncompanyNameChanging(string value);
    partial void OncompanyNameChanged();
    partial void OncompanyCodeChanging(string value);
    partial void OncompanyCodeChanged();
    partial void OncompanyPhoneChanging(string value);
    partial void OncompanyPhoneChanged();
    partial void OncompanyAddressChanging(string value);
    partial void OncompanyAddressChanged();
    partial void On取消开牌时限Changing(System.Nullable<int> value);
    partial void On取消开牌时限Changed();
    partial void On取消开房时限Changing(System.Nullable<int> value);
    partial void On取消开房时限Changed();
    partial void On删除支出时限Changing(System.Nullable<int> value);
    partial void On删除支出时限Changed();
    partial void On退钟时限Changing(System.Nullable<int> value);
    partial void On退钟时限Changed();
    partial void On技师条数Changing(System.Nullable<int> value);
    partial void On技师条数Changed();
    partial void On启用鞋部Changing(System.Nullable<bool> value);
    partial void On启用鞋部Changed();
    partial void On鞋部条数Changing(System.Nullable<int> value);
    partial void On鞋部条数Changed();
    partial void On启用会员卡密码Changing(System.Nullable<bool> value);
    partial void On启用会员卡密码Changed();
    partial void On输入手牌Changing(System.Nullable<bool> value);
    partial void On输入手牌Changed();
    partial void On启用结账监控Changing(System.Nullable<bool> value);
    partial void On启用结账监控Changed();
    partial void On结账视频长度Changing(string value);
    partial void On结账视频长度Changed();
    partial void On启用手牌锁Changing(System.Nullable<bool> value);
    partial void On启用手牌锁Changed();
    partial void On开业时间Changing(System.Nullable<int> value);
    partial void On开业时间Changed();
    #endregion
		
		public Options()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_companyName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string companyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				if ((this._companyName != value))
				{
					this.OncompanyNameChanging(value);
					this.SendPropertyChanging();
					this._companyName = value;
					this.SendPropertyChanged("companyName");
					this.OncompanyNameChanged();
				}
			}
		}
		
		[Column(Storage="_companyCode", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string companyCode
		{
			get
			{
				return this._companyCode;
			}
			set
			{
				if ((this._companyCode != value))
				{
					this.OncompanyCodeChanging(value);
					this.SendPropertyChanging();
					this._companyCode = value;
					this.SendPropertyChanged("companyCode");
					this.OncompanyCodeChanged();
				}
			}
		}
		
		[Column(Storage="_companyPhone", DbType="NVarChar(MAX)")]
		public string companyPhone
		{
			get
			{
				return this._companyPhone;
			}
			set
			{
				if ((this._companyPhone != value))
				{
					this.OncompanyPhoneChanging(value);
					this.SendPropertyChanging();
					this._companyPhone = value;
					this.SendPropertyChanged("companyPhone");
					this.OncompanyPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_companyAddress", DbType="NVarChar(MAX)")]
		public string companyAddress
		{
			get
			{
				return this._companyAddress;
			}
			set
			{
				if ((this._companyAddress != value))
				{
					this.OncompanyAddressChanging(value);
					this.SendPropertyChanging();
					this._companyAddress = value;
					this.SendPropertyChanged("companyAddress");
					this.OncompanyAddressChanged();
				}
			}
		}
		
		[Column(Storage="_取消开牌时限", DbType="Int")]
		public System.Nullable<int> 取消开牌时限
		{
			get
			{
				return this._取消开牌时限;
			}
			set
			{
				if ((this._取消开牌时限 != value))
				{
					this.On取消开牌时限Changing(value);
					this.SendPropertyChanging();
					this._取消开牌时限 = value;
					this.SendPropertyChanged("取消开牌时限");
					this.On取消开牌时限Changed();
				}
			}
		}
		
		[Column(Storage="_取消开房时限", DbType="Int")]
		public System.Nullable<int> 取消开房时限
		{
			get
			{
				return this._取消开房时限;
			}
			set
			{
				if ((this._取消开房时限 != value))
				{
					this.On取消开房时限Changing(value);
					this.SendPropertyChanging();
					this._取消开房时限 = value;
					this.SendPropertyChanged("取消开房时限");
					this.On取消开房时限Changed();
				}
			}
		}
		
		[Column(Storage="_删除支出时限", DbType="Int")]
		public System.Nullable<int> 删除支出时限
		{
			get
			{
				return this._删除支出时限;
			}
			set
			{
				if ((this._删除支出时限 != value))
				{
					this.On删除支出时限Changing(value);
					this.SendPropertyChanging();
					this._删除支出时限 = value;
					this.SendPropertyChanged("删除支出时限");
					this.On删除支出时限Changed();
				}
			}
		}
		
		[Column(Storage="_退钟时限", DbType="Int")]
		public System.Nullable<int> 退钟时限
		{
			get
			{
				return this._退钟时限;
			}
			set
			{
				if ((this._退钟时限 != value))
				{
					this.On退钟时限Changing(value);
					this.SendPropertyChanging();
					this._退钟时限 = value;
					this.SendPropertyChanged("退钟时限");
					this.On退钟时限Changed();
				}
			}
		}
		
		[Column(Storage="_技师条数", DbType="Int")]
		public System.Nullable<int> 技师条数
		{
			get
			{
				return this._技师条数;
			}
			set
			{
				if ((this._技师条数 != value))
				{
					this.On技师条数Changing(value);
					this.SendPropertyChanging();
					this._技师条数 = value;
					this.SendPropertyChanged("技师条数");
					this.On技师条数Changed();
				}
			}
		}
		
		[Column(Storage="_启用鞋部", DbType="Bit")]
		public System.Nullable<bool> 启用鞋部
		{
			get
			{
				return this._启用鞋部;
			}
			set
			{
				if ((this._启用鞋部 != value))
				{
					this.On启用鞋部Changing(value);
					this.SendPropertyChanging();
					this._启用鞋部 = value;
					this.SendPropertyChanged("启用鞋部");
					this.On启用鞋部Changed();
				}
			}
		}
		
		[Column(Storage="_鞋部条数", DbType="Int")]
		public System.Nullable<int> 鞋部条数
		{
			get
			{
				return this._鞋部条数;
			}
			set
			{
				if ((this._鞋部条数 != value))
				{
					this.On鞋部条数Changing(value);
					this.SendPropertyChanging();
					this._鞋部条数 = value;
					this.SendPropertyChanged("鞋部条数");
					this.On鞋部条数Changed();
				}
			}
		}
		
		[Column(Storage="_启用会员卡密码", DbType="Bit")]
		public System.Nullable<bool> 启用会员卡密码
		{
			get
			{
				return this._启用会员卡密码;
			}
			set
			{
				if ((this._启用会员卡密码 != value))
				{
					this.On启用会员卡密码Changing(value);
					this.SendPropertyChanging();
					this._启用会员卡密码 = value;
					this.SendPropertyChanged("启用会员卡密码");
					this.On启用会员卡密码Changed();
				}
			}
		}
		
		[Column(Storage="_输入手牌", DbType="Bit")]
		public System.Nullable<bool> 输入手牌
		{
			get
			{
				return this._输入手牌;
			}
			set
			{
				if ((this._输入手牌 != value))
				{
					this.On输入手牌Changing(value);
					this.SendPropertyChanging();
					this._输入手牌 = value;
					this.SendPropertyChanged("输入手牌");
					this.On输入手牌Changed();
				}
			}
		}
		
		[Column(Storage="_启用结账监控", DbType="Bit")]
		public System.Nullable<bool> 启用结账监控
		{
			get
			{
				return this._启用结账监控;
			}
			set
			{
				if ((this._启用结账监控 != value))
				{
					this.On启用结账监控Changing(value);
					this.SendPropertyChanging();
					this._启用结账监控 = value;
					this.SendPropertyChanged("启用结账监控");
					this.On启用结账监控Changed();
				}
			}
		}
		
		[Column(Storage="_结账视频长度", DbType="NVarChar(MAX)")]
		public string 结账视频长度
		{
			get
			{
				return this._结账视频长度;
			}
			set
			{
				if ((this._结账视频长度 != value))
				{
					this.On结账视频长度Changing(value);
					this.SendPropertyChanging();
					this._结账视频长度 = value;
					this.SendPropertyChanged("结账视频长度");
					this.On结账视频长度Changed();
				}
			}
		}
		
		[Column(Storage="_启用手牌锁", DbType="Bit")]
		public System.Nullable<bool> 启用手牌锁
		{
			get
			{
				return this._启用手牌锁;
			}
			set
			{
				if ((this._启用手牌锁 != value))
				{
					this.On启用手牌锁Changing(value);
					this.SendPropertyChanging();
					this._启用手牌锁 = value;
					this.SendPropertyChanged("启用手牌锁");
					this.On启用手牌锁Changed();
				}
			}
		}
		
		[Column(Storage="_开业时间", DbType="Int")]
		public System.Nullable<int> 开业时间
		{
			get
			{
				return this._开业时间;
			}
			set
			{
				if ((this._开业时间 != value))
				{
					this.On开业时间Changing(value);
					this.SendPropertyChanging();
					this._开业时间 = value;
					this.SendPropertyChanged("开业时间");
					this.On开业时间Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
