<?xml version="1.0" encoding="utf-8"?>
<Database Name="BathDB" Class="WatcherDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CAI-PC\SQLEXPRESS;Initial Catalog=BathDB;Persist Security Info=True;User ID=sa" SettingsObjectName="YouSoftBathWatcher.Properties.Settings" SettingsPropertyName="BathDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Seat" Member="Seat">
    <Type Name="Seat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="typeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="systemId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="openTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="openEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="payTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="payEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="discountEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="memberDiscount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="memberPromotionId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="freeEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="chainId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ordering" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="paying" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="unwarn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="roomStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="deposit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="cardId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="jobId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="onDuty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="salary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="entryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idCard" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderClock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="startTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="serverTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="techStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="room" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClearTable" Member="ClearTable">
    <Type Name="ClearTable">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clearTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="proceeded" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Options" Member="Options">
    <Type Name="Options">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="companyName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="companyCode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="companyPhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="companyAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="取消开牌时限" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="取消开房时限" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="删除支出时限" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="退钟时限" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="技师条数" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="启用鞋部" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="鞋部条数" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="启用会员卡密码" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="启用结账监控" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="结账视频长度" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="启用手牌锁" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="开业时间" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="启用客房面板" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="包房等待时限" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="下钟提醒" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="启用ID手牌锁" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="允许手工输入手牌号开牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="允许手工输入手牌号结账" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="录单输入单据编号" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="结账未打单锁定手牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="营业报表格式" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="结账打印结账单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="结账打印存根单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="结账打印取鞋小票" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="抹零限制" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="手牌锁类型" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="自动加收过夜费" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="过夜费起点" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="过夜费终点" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="启用分单结账" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="启用员工服务卡" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="台位类型分页显示" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="提成报表格式" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="自动感应手牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="systemId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="openTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="openEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="payTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="payEmployee" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="promotionMemberId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="promotionAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="memberId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="discountEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="serverEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cash" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bankUnion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="creditCard" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="coupon" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="groupBuy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="zero" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="server" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="deducted" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="changes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="wipeZero" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="macAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="abandon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="departmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="systemdId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menu">
    <Type Name="Menu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="catgoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="technician" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="techRatioType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="onRatio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="orderRatio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="timeLimitHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timeLimitMiniute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="addAutomatic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="addType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="addMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="timeLimitType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="waiter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="waiterRatio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="waiterRatioType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Catgory" Member="Catgory">
    <Type Name="Catgory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="kitchPrinterName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="systemId" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="number" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="priceType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="money" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="technician" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="techType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="startTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inputTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="inputEmployee" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="deleteEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="donorEmployee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="comboId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="paid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="accountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="billId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="stopTiming" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="departmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Authority" Member="Authority">
    <Type Name="Authority">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="emplyeeId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="jobId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="开牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="取消开牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="更换手牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="锁定解锁" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="解除警告" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="停用启用" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="添加备注" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="挂失手牌" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="完整点单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="可见本人点单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="退单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="手工打折" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="签字免单" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="转账" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="重新结账" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="结账" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="技师管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="收银汇总统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="包房管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="收银单据查询" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="录单汇总" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="营业信息查看" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="售卡" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="充值" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="挂失" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="补卡" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="读卡" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="扣卡" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="卡入库" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="异常状况统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="提成统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="手工打折汇总" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="项目报表" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="信用卡统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="营业报表" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="退免单汇总" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="支出统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="收银员收款统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="月报表" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="往来单位账目" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="会员积分设置" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="优惠方案" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="会员分析" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="会员管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="会员消费统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="会员售卡及充值统计" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="手牌管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="券类管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="客户管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="项目档案管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="客房管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="员工管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="权限管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="套餐管理" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="库存参数" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="仓库设定" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="补货标准" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="进货入库" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="现有库存" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="调货补货" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="盘点清册" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="盘点调整" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="应付账款" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="系统设置" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="数据优化" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="收银报表" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>